### PR TITLE
Fix error due lack of continuing to support librsvg 2.40.x and also newer librsvg

### LINKED ISSUE #205: error due lack of continuing to support librsvg 2.40.x
Commit 1533e8def33bd3e1d7f4734206af4a66b51b9960 uses too new functions of librsvg

instead, let's add some conditional wheantime some people migrating softly so that it still builds with librsvg 2.40.x (which was the last versions fully in C) while we use newer code and no warnings when using newer versions

without that i got this error:

```
[   53s] src/icon.c: In function 'get_svg_icon':
[   53s] src/icon.c:104:2: error: unknown type name 'RsvgRectangle'; did you mean 'XRectangle'?
[   53s]   RsvgRectangle viewport = {
[   53s]   ^~~~~~~~~~~~~
[   53s]   XRectangle
[   53s] src/icon.c:105:3: error: field name not in record or union initializer
[   53s]    .x = 0,
[   53s]    ^
[   53s] src/icon.c:105:3: note: (near initialization for 'viewport')
[   53s] src/icon.c:106:3: error: field name not in record or union initializer
[   53s]    .y = 0,
[   53s]    ^
[   53s] src/icon.c:106:3: note: (near initialization for 'viewport')
[   53s] src/icon.c:106:8: warning: excess elements in scalar initializer
[   53s]    .y = 0,
[   53s]         ^
[   53s] src/icon.c:106:8: note: (near initialization for 'viewport')
[   53s] src/icon.c:107:3: error: field name not in record or union initializer
[   53s]    .width = size,
[   53s]    ^
[   53s] src/icon.c:107:3: note: (near initialization for 'viewport')
[   53s] src/icon.c:107:12: warning: excess elements in scalar initializer
[   53s]    .width = size,
[   53s]             ^~~~
[   53s] src/icon.c:107:12: note: (near initialization for 'viewport')
[   53s] src/icon.c:108:3: error: field name not in record or union initializer
[   53s]    .height = size,
[   53s]    ^
[   53s] src/icon.c:108:3: note: (near initialization for 'viewport')
[   53s] src/icon.c:108:13: warning: excess elements in scalar initializer
[   53s]    .height = size,
[   53s]              ^~~~
[   53s] src/icon.c:108:13: note: (near initialization for 'viewport')
[   53s] src/icon.c:122:2: warning: implicit declaration of function 'rsvg_handle_render_document'; did you mean 'rsvg_handle_render_cairo'? [-Wimplicit-function-declaration]
[   53s]   rsvg_handle_render_document(svg, cr, &viewport, &err);
[   53s]   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[   53s]   rsvg_handle_render_cairo
[   53s] make[1]: *** [Makefile:76: icon.o] Error 1
[   53s] make[1]: Leaving directory '/usr/src/packages/BUILD'
[   53s] dh_auto_build: make -j1 returned exit code 2
[   53s] make: *** [debian/rules:35: binary] Error 2
[   53s] dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
[   53s] ### VM INTERACTION START ###
[   53s] Failed to write utmp record: Read-only file system
[   53s] Powering off.
[   53s] [   46.304436][ T9720] reboot: Power down
[   53s] ### VM INTERACTION END ###
[   53s] 
[   53s] i02-ch2c failed "build jgmenu_4.4.1-1.dsc" at Tue Nov 14 15:20:15 UTC 2023.
[   53s] 
```

### PR DESCRIPTION
**Pull request by mckaygerhard**
Commit 1533e8d uses too new functions of librsvg

instead, let's add some conditional wheantime some people migrating softly so that it still builds with librsvg 2.40.x (which was the last versions fully in C) while we use newer code and no warnings when using newer versions

fixes #205

### CODE REVIEW

**Comment by johanmalm** [comment]
Looks good. Thanks!
